[project]
name = "inl-pjatk-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pandas>=2.3.3",
]

[dependency-groups]
dev = [
    "datasets>=4.4.2",
    "pytest>=9.0.2",
]
